/**
 * Format of vector tiles generated by geojsonvt
 * @see https://github.com/mapbox/geojson-vt
 */
export interface VectorTileVT {
  id?: string; // = typeof feature.id === 'number' ? feature.id : undefined;
  type: number; //  = feature.type;
  rawGeometry: any; //  = feature.type === 1 ? [feature.geometry] : feature.geometry;
  properties: any[]; // = feature.tags;
  extent: number; // = extent || 4096;
}
